var fiftyTwoDeck = [
    [1, "images/PNG-cards-1.3/ace_of_spades.png"],
    [1, "images/PNG-cards-1.3/two_of_spades.png"],
    [1, "images/PNG-cards-1.3/three_of_spades.png"],
    [1, "images/PNG-cards-1.3/four_of_spades.png"],
    [1, "images/PNG-cards-1.3/five_of_spades.png"],
    [1, "images/PNG-cards-1.3/six_of_spades.png"],
    [1, "images/PNG-cards-1.3/seven_of_spades.png"],
    [1, "images/PNG-cards-1.3/eight_of_spades.png"],
    [1, "images/PNG-cards-1.3/nine_of_spades.png"],
    [1, "images/PNG-cards-1.3/ten_of_spades.png"],
    [1, "images/PNG-cards-1.3/jack_of_spades2.png"],
    [1, "images/PNG-cards-1.3/ace_of_spades2.png"],
    [1, "images/PNG-cards-1.3/ace_of_spades2.png"],

    [1, "images/PNG-cards-1.3/ace_of_hearts.png"],
    [1, "images/PNG-cards-1.3/two_of_hearts.png"],
    [1, "images/PNG-cards-1.3/three_of_hearts.png"],
    [1, "images/PNG-cards-1.3/four_of_hearts.png"],
    [1, "images/PNG-cards-1.3/five_of_hearts.png"],
    [1, "images/PNG-cards-1.3/six_of_hearts.png"],
    [1, "images/PNG-cards-1.3/seven_of_hearts.png"],
    [1, "images/PNG-cards-1.3/eight_of_hearts.png"],
    [1, "images/PNG-cards-1.3/nine_of_hearts.png"],
    [1, "images/PNG-cards-1.3/ten_of_hearts.png"],
    [1, "images/PNG-cards-1.3/jack_of_hearts2.png"],
    [1, "images/PNG-cards-1.3/ace_of_hearts2.png"],
    [1, "images/PNG-cards-1.3/ace_of_hearts2.png"],

    [1, "images/PNG-cards-1.3/ace_of_clubs.png"],
    [1, "images/PNG-cards-1.3/two_of_clubs.png"],
    [1, "images/PNG-cards-1.3/three_of_clubs.png"],
    [1, "images/PNG-cards-1.3/four_of_clubs.png"],
    [1, "images/PNG-cards-1.3/five_of_clubs.png"],
    [1, "images/PNG-cards-1.3/six_of_clubs.png"],
    [1, "images/PNG-cards-1.3/seven_of_clubs.png"],
    [1, "images/PNG-cards-1.3/eight_of_clubs.png"],
    [1, "images/PNG-cards-1.3/nine_of_clubs.png"],
    [1, "images/PNG-cards-1.3/ten_of_clubs.png"],
    [1, "images/PNG-cards-1.3/jack_of_clubs2.png"],
    [1, "images/PNG-cards-1.3/ace_of_clubs2.png"],
    [1, "images/PNG-cards-1.3/ace_of_clubs2.png"],

    [1, "images/PNG-cards-1.3/ace_of_diamonds.png"],
    [1, "images/PNG-cards-1.3/two_of_diamonds.png"],
    [1, "images/PNG-cards-1.3/three_of_diamonds.png"],
    [1, "images/PNG-cards-1.3/four_of_diamonds.png"],
    [1, "images/PNG-cards-1.3/five_of_diamonds.png"],
    [1, "images/PNG-cards-1.3/six_of_diamonds.png"],
    [1, "images/PNG-cards-1.3/seven_of_diamonds.png"],
    [1, "images/PNG-cards-1.3/eight_of_diamonds.png"],
    [1, "images/PNG-cards-1.3/nine_of_diamonds.png"],
    [1, "images/PNG-cards-1.3/ten_of_diamonds.png"],
    [1, "images/PNG-cards-1.3/jack_of_diamonds2.png"],
    [1, "images/PNG-cards-1.3/ace_of_diamonds2.png"],
    [1, "images/PNG-cards-1.3/ace_of_diamonds2.png"],

];

export {fiftyTwoDeck};